### ISSUE TITLE
Problem in 04_02_06_lda.ipynb

### ISSUE THREAD

**Issue by matthewabarlow** [wjbmattingly/python_for_dh#11]
In the below code, the id_docs variable is not defined anywhere in the file and gives an error when run.

vis = pyLDAvis.gensim_models.prepare(lda_model, id_docs, id2word, mds="mmds", R=30)

**Comment by wjbmattingly** [comment]
Thanks for catching this! I have now fixed it and replaced id_docs with corpus.
