### ISSUE TITLE
Issue on page /04_topic_modeling/04_02_06_lda.html

### ISSUE THREAD

**Issue by Ksquaredliz** [wjbmattingly/python_for_dh#13]
Having trouble with 
vis = pyLDAvis.gensim_models.prepare(lda_model, id_docs, id2word, mds="mmds", R=30)
Output is:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_7800/2698686978.py in <module>
----> 1 vis = pyLDAvis.gensim_models.prepare(lda_model, id_docs, id2word, mds="mmds", R=30)

NameError: name 'id_docs' is not defined

**Comment by wjbmattingly** [comment]
Thanks for catching this! I have now fixed it and replaced id_docs with corpus.

**Comment by Ksquaredliz** [comment]
Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wjbmattingly** [comment]
No problem!
